export const UNIVERSIDADES: string = 'Universidades'
export const COOPERANTES: string = 'Cooperantes'
export const ONG: string = 'Organizaciones Relacionadas'
export const COOPERANTES_REDSOC: string = 'Cooperantes Redsoc'
export const ADMINISTRACION : string = 'Administración'